sudo: true
language: python
python:
    - "2.7"
    - "3.6"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install gcc-4.8 g++-4.8 -y -qq
  - export CXX=g++-4.8 CC=gcc-4.8
  - pip install numpy
  - pip install pandas
  - pip install biopython
  - pip install scipy

install:
    - make
    - sudo make install

script:
    - make test
