#!/usr/bin/env python
# -*- coding: utf-8 -*-

# fluidigm2purc
# Written by PD Blischak

from __future__ import print_function
import subprocess as sps
import sys
import os
import argparse
import gzip
import itertools

#### header and version info. ##################################################

__version__ = "This is fluidigm2purc v0.1.0-alpha (April 2017)."

__header__ = """**********************************************
fluidigm2purc (v0.1.0-alpha)

Processing of paired-end FASTQ data from the
Fluidigm platform for input to PURC.
**********************************************
"""

#### PHRED conversion dictionary. ##############################################
PHRED = {'!': 1.00, '"': 0.79433, '#': 0.63096, '$': 0.50119, '%': 0.39811,
         '&': 0.31623, '\'': 0.25119, '(': 0.19953, ')': 0.15849, '*': 0.12589,
         '+': 0.10000, ',': 0.07943, '-': 0.06310, '.': 0.05012, '/': 0.03981,
         '0': 0.03162, '1': 0.02512, '2': 0.01995, '3': 0.01585, '4': 0.01259,
         '5': 0.01000, '6': 0.00784, '7': 0.00631, '8': 0.00501, '9': 0.00398,
         ':': 0.00316, ';': 0.00251, '<': 0.00200, '=': 0.00158, '>': 0.00126,
         '?': 0.00100, '@': 0.00079, 'A': 0.00063, 'B': 0.00050, 'C': 0.00040,
         'D': 0.00032, 'E': 0.00025, 'F': 0.00020, 'G': 0.00016, 'H': 0.00013,
         'I': 0.00010, 'J': 0.00008, 'K': 0.00006}

#### functions to run executables, process FASTQs. #############################

def run_sickle(prefix, outname, quality, min_length):
    """
    Runs the program Sickle to trim and filters reads.

    Sickle:
    Joshi NA, Fass JN. (2011). Sickle: A sliding-window, adaptive, quality-based
    trimming tool for FastQ files (Version 1.33) [Software].
    Available at https://github.com/najoshi/sickle.
    """
    print("\n**** 1. Trimming and filtering paired-end reads with Sickle ****\n\n")

    # test the executable first
    print("  Checking Sickle executable...    ", end='')
    test_proc = sps.Popen(['sickle'], stdout=sps.PIPE, stderr=sps.PIPE, shell=True)
    (out, err) = test_proc.communicate()
    if not str(out).startswith('\nUsage'):
        sys.exit("\n\n** ERROR: could not execute Sickle **\n\n")
    else:
        print("Good\n")

    sickle_cmd = [
        "sickle", "pe",
        "-f", prefix+"_R1.fastq.gz",
        "-r", prefix+"_R2.fastq.gz",
        "-t", "sanger",
        "-o", outname+"-sickled_R1.fastq.gz",
        "-p", outname+"-sickled_R2.fastq.gz",
        "-s", outname+"-sickled_singles.fastq.gz",
        "-q", str(quality),
        "-l", str(min_length),
        "-g"
    ]
    proc = sps.call(sickle_cmd)#, stdin=sps.PIPE, stdout=sps.PIPE, close_fds=True)

def run_flash2(outname, threads):
    """
    Run the program FLASH2 to merge paired-end reads that are filtered and trimmed
    by Sickle. The command line arguments are the same that are used by the
    dbcAplicons script 'reduce_amplicons.R'.

    FLASH2:
    Tanja Magoč and Steven L. Salzberg. (2011). FLASH: fast length adjustment of
    short reads to improve genome assemblies. Bioinformatics 27:
    http://bioinformatics.oxfordjournals.org/content/27/21/2957.full
    """
    print("\n**** 2. Merging reads using FLASH2 ****\n")

    # test the executable first
    print("  Checking FLASH2 executable...    ", end='')
    test_proc = sps.Popen(['flash2'], stdout=sps.PIPE, stderr=sps.PIPE, shell=True)
    (out, err) = test_proc.communicate()
    if not str(err).startswith('Usage'):
        sys.exit("\n\n** ERROR: Could not execute FLASH2 **\n\n")
    else:
        print("Good\n")

    print("  Note: FLASH2 always produces a warning about adapter trimming.")
    print("        It can be safely ignored.\n\n")

    flash2_cmd = [
        "flash2",
        "--max-overlap=600",
        "--allow-outies",
        "-t", str(threads),
        "-x", "0.25",
        "-z", "--quiet",
        "-o", outname+"-flashed",
        outname+"-sickled_R1.fastq.gz",
        outname+"-sickled_R2.fastq.gz"
    ]
    proc = sps.call(flash2_cmd)

def _run_pear(prefix, outname, quality, length, threads):
    """
    **** EXPERIMENTAL ****

    Run the program PEAR to merge paired-end reads. Performs read trimming
    so we don't need to do this ahead of time, but can do it using Sickle
    if you want.

    PEAR:
    J. Zhang, K. Kobert, T. Flouri, A. Stamatakis. PEAR: A fast and accurate
    Illumina Paired-End reAd mergeR. Bioinformatics 30(5): 614-620, 2014.
    """
    print("\n**** 1&2. Trimming and merging reads using PEAR ****\n")
    # test the executable first
    print("  Checking PEAR executable...    ", end='')
    test_proc = sps.Popen(['pear'], stdout=sps.PIPE, stderr=sps.PIPE, shell=True)
    (out, err) = test_proc.communicate()
    if not str(out).startswith(' ____'):
        sys.exit("\n\n** ERROR: Could not execute PEAR **\n\n")
    else:
        print("Good\n")

    pear_cmd = [
        "pear",
        "-f", prefix + "_R1.fastq.gz",
        "-r", prefix + "_R2.fastq.gz",
        "-o", outname,
        "-q", str(quality),
        "-j", str(threads),
        "-k"
    ]
    proc = sps.call(pear_cmd)

# Define global list variables for taxa and loci.
# Used for writing logfile.
taxa = []
loci = []
per_locus_error = {}
def PURCify_fastq(outname, gz):
    """
    Function for reading in FASTQ files and converting to PURC-style FASTA.
    Uses taxon and locus names in the FASTQ sequence headers. Prints unmerged
    reads from FLASH2 with 8 n's in between the two paired reads.
    """
    print("\n**** 3. PURCifying FASTQ files ****\n\n")
    locus_outfiles = {}
    if not os.path.exists("./"+outname+"-FASTA"):
        os.makedirs("./"+outname+"-FASTA")
    else:
        print("  Output directory for FASTA files alread exists ("+outname+"-FASTA/).")
        print("  Please use a different outname to prevent overwriting it.\n")
        sys.exit(-1)
    line_counter = 1
    read_counter = 1
    for line in gzip.open(outname+"-flashed.extendedFrags.fastq.gz"):
        if line_counter == 1:
            info = line.strip().split(" ")[1].split(":")
            if info[-1] not in locus_outfiles.keys():
                locus_outfiles[info[-1]] = open("./"+outname+"-FASTA/"+info[-1]+".fasta", 'w')
            print(">", info[-2], "|", info[-1], "|", str(read_counter), file=locus_outfiles[info[-1]], sep='')
            if info[-1] not in loci:
                per_locus_error[info[-1]] = []
                loci.append(info[-1])
            if info[-2] not in taxa:
                taxa.append(info[-2])
            line_counter = 2
            read_counter += 1
            prev_locus = info[-1]
        elif line_counter == 2:
            print(line.strip(), file=locus_outfiles[prev_locus], sep='')
            line_counter = 3
        elif line_counter == 3:
            line_counter = 4
        elif line_counter == 4:
            per_locus_error[info[-1]].append(convert_phred(line.strip()))
            line_counter = 1
        else:
            raise_error("Something done messed up.", line_counter)

    # Combine unmerged reads with 8 N's in between them.
    unmerged1 = gzip.open(outname+"-flashed.notCombined_1.fastq.gz")
    unmerged2 = gzip.open(outname+"-flashed.notCombined_2.fastq.gz")
    line_counter = 1
    for line1, line2 in itertools.izip(unmerged1,unmerged2):
        if line_counter == 1:
            info1 = line1.strip().split(" ")[1].split(":")
            info2 = line2.strip().split(" ")[1].split(":")
            assert info1[-1] == info2[-1]
            assert info1[-2] == info2[-2]
            if info1[-1] not in locus_outfiles.keys():
                locus_outfiles[info1[-1]] = open("./"+outname+"-FASTA/"+info1[-1]+".fasta", 'w')
            print(">", info1[-2], "|", info1[-1], "|", str(read_counter), file=locus_outfiles[info1[-1]], sep='')
            if info1[-1] not in loci:
                per_locus_error[info[-1]] = []
                loci.append(info1[-1])
            if info1[-2] not in taxa:
                taxa.append(info1[-2])
            line_counter = 2
            read_counter += 1
            prev_locus = info1[-1]
        elif line_counter == 2:
            print(line1.strip(), "NNNNNNNN", line2.strip(), file=locus_outfiles[prev_locus], sep='')
            line_counter = 3
        elif line_counter == 3:
            line_counter = 4
        elif line_counter == 4:
            per_locus_error[info[-1]].append(convert_phred(line1.strip()+line2.strip()))
            line_counter = 1
        else:
            raise_error("Something done messed up.", line_counter)

#### some utility functions. ###################################################

def raise_error(error_message, bad_arg):
    """
    Prints error message and exits program.
    """
    print("\n** ERROR: ", error_message, " **\n", sep='')
    print("  => Option provided: ", bad_arg, "\n", sep='')
    sys.exit(-1)

def write_log(outname, args, program):
    """
    Writes summary of fluidigm2purc run.
    Prints taxa and loci retained after filtering.
    Prints average probability of sequencing error per locus.
    """
    logfile = open(outname+".log", 'w')
    locus_errfile = open(outname+"-locus-err.txt", 'w')
    print(__header__, file=logfile)
    print("Command line call:\n  ", end='', file=logfile)
    for a in args:
        print(a, " ", sep='', end='', file=logfile)

    if program == "all" or program == "PURCify":
        print("\n\nTaxa retained:\n", end='', file=logfile)
        for t in taxa:
            print("  ", t, file=logfile)
        print("\nLoci retained:\n", end='', file=logfile)
        for l in loci:
            print("  ", l, file=logfile)

    for k in per_locus_error.keys():
        print(k, mean(per_locus_error[k]), sep='\t', file=locus_errfile)

def mean(numbers):
    """
    Caclulate the main of a list.
    """
    return float(sum(numbers)) / max(len(numbers), 1)

def convert_phred(phred_string):
    """
    Convert a string of PHRED qulity scores to probabilities and take the mean.
    """
    return mean([PHRED[s] for s in phred_string])

#### main functions. ###########################################################

def main():
    """
    Main function for fluidigm2purc.

    It parses command line arguments and runs three main steps:
        1. Paired end trimming and filtering of reads using Sickle.
        2. Read merging (and optional trimming) using FLASH2.
        3. PURCifying merged and unmerged FASTQ files to FASTA with
           modified sequence headers for input to PURC.
    """
    parser = argparse.ArgumentParser(description="Options for fluidigm2purc",
                                     add_help=True)
    parser.add_argument('-v', '--version', action="version",
                        version=__version__)

    required = parser.add_argument_group("required arguments")
    required.add_argument('-f', '--fastq_prefix', action="store", required=True,
                          metavar='\b', help="prefix for paired-end FASTQ files")

    additional = parser.add_argument_group("additional arguments")
    additional.add_argument('-p', '--program', action="store", type=str, default="all",
                            metavar='\b', help="program(s) to run [default=all; options=sickle, flash2, PURCify, all]")
    additional.add_argument('-o', '--outname', action="store", type=str, default="output",
                            metavar='\b', help="base name for output fasta file [default=output]")
    additional.add_argument('-j', '--nthreads', action="store", type=int, default=1,
                            metavar='\b', help="number of threads to use for executables [default=1]")
    additional.add_argument('-q', '--quality', action="store", type=int, default=20,
                            metavar='\b', help="PHRED quality score cutoff [default=20]")
    additional.add_argument('-l', '--length', action="store", type=int, default=100,
                            metavar='\b', help="minimum length for Sickle trimming [default=100]")
    additional.add_argument('-g', '--gzip', action="store_true", default=False,
                            help="flag to compress output fasta")

    args    = parser.parse_args()
    prefix  = args.fastq_prefix
    outname = args.outname
    threads = args.nthreads
    quality = args.quality
    length  = args.length
    program = args.program
    gzip    = args.gzip

    print("\n", __header__, sep='')

    if program == "all":
        run_sickle(prefix, outname, quality, length)
        run_flash2(outname, threads)
        PURCify_fastq(outname, gzip)
    elif program == "_pear":
        _run_pear(prefix, outname, quality, length, threads)
    elif program == "sickle":
        run_sickle(prefix, outname, quality, length)
    elif program == "flash2":
        run_flash2(outname, threads)
    elif program == "PURCify":
        PURCify_fastq(outname, gzip)
    else:
        raise_error("Invalid program spcified. Choose one of the following: "\
                    "'all', 'sickle', 'flash2', 'PURCify'.", program)

    write_log(outname, sys.argv, program)
    print("**** DONE: Run info written to '" + outname + ".log' ****\n", sep='')

if __name__ == "__main__":
    """
    Run the main function when called from command line.
    """
    main()
